secvest_set_mode:
  name: Set Secvest mode
  description: Set alarm mode (set/partset/unset)
  fields:
    mode:
      name: Mode
      description: One of set, partset, unset
      required: true
      selector:
        select:
          options:
            - set
            - partset
            - unset
